#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : deprecated-zope.testing
Version  : 4.7
Release  : 26
URL      : https://files.pythonhosted.org/packages/a2/95/2a2ed23bbb3dcf7916ff39bf349314304f6e4c4dd77d86e3930def52b45e/zope.testing-4.7.tar.gz
Source0  : https://files.pythonhosted.org/packages/a2/95/2a2ed23bbb3dcf7916ff39bf349314304f6e4c4dd77d86e3930def52b45e/zope.testing-4.7.tar.gz
Summary  : Zope testing helpers
Group    : Development/Tools
License  : ZPL-2.1
Requires: deprecated-zope.testing-license = %{version}-%{release}
Requires: deprecated-zope.testing-python = %{version}-%{release}
Requires: setuptools
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : setuptools
BuildRequires : setuptools-legacypython
BuildRequires : tox
BuildRequires : virtualenv

%description
=================
``zope.testing``
=================
.. image:: https://img.shields.io/pypi/v/zope.testing.svg
:target: https://pypi.python.org/pypi/zope.testing/
:alt: Latest Version

%package legacypython
Summary: legacypython components for the deprecated-zope.testing package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-zope.testing package.


%package license
Summary: license components for the deprecated-zope.testing package.
Group: Default

%description license
license components for the deprecated-zope.testing package.


%package python
Summary: python components for the deprecated-zope.testing package.
Group: Default

%description python
python components for the deprecated-zope.testing package.


%prep
%setup -q -n zope.testing-4.7

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554330553
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecated-zope.testing
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/deprecated-zope.testing/LICENSE.txt
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecated-zope.testing/LICENSE.txt

%files python
%defattr(-,root,root,-)
